In [45]:
import os
import pandas as pd
import sqlalchemy

In [46]:
os.chdir("/home/michal/Downloads")

In [47]:
os.listdir()

['firefox-57.0.2.tar.bz2', 'Kwotowania bloomberg.csv']

In [60]:
data = pd.read_csv("Kwotowania bloomberg.csv", sep = ';', decimal = ',')

In [61]:
data.columns

Index(['INSTRUMENT', 'Date', 'OPEN', 'HIGH', 'LOW', 'CLOSE'], dtype='object')

In [62]:
data.columns = ['INSTRUMENT', 'datetime', 'open', 'high', 'low', 'close']

In [63]:
data['datetime'] = pd.to_datetime(data['datetime'], format = "%Y-%m-%d %H:%M")

In [54]:
gbpusd = data[data['INSTRUMENT'] == 'GBPUSD']

In [55]:
gbpusd = gbpusd.drop('INSTRUMENT', 1)

In [56]:
gbpusd['volume'] = 0
gbpusd['source'] = 'bloomberg'
gbpusd

,datetime,open,high,low,close,volume,source
23516,2017-11-13 09:01:00,1.30965,1.30975,1.30945,1.30945,0,bloomberg
23517,2017-11-13 09:02:00,1.30945,1.30965,1.30935,1.30955,0,bloomberg
23518,2017-11-13 09:03:00,1.30955,1.30965,1.30945,1.30945,0,bloomberg
23519,2017-11-13 09:04:00,1.30945,1.31005,1.30945,1.30980,0,bloomberg
23520,2017-11-13 09:05:00,1.30980,1.31005,1.30980,1.31000,0,bloomberg
23521,2017-11-13 09:06:00,1.31000,1.31010,1.30975,1.31005,0,bloomberg
23522,2017-11-13 09:07:00,1.31005,1.31015,1.30985,1.31005,0,bloomberg
23523,2017-11-13 09:08:00,1.31005,1.31010,1.30995,1.31000,0,bloomberg
23524,2017-11-13 09:09:00,1.31000,1.31020,1.30995,1.31010,0,bloomberg
23525,2017-11-13 09:10:00,1.31010,1.31030,1.30995,1.31005,0,bloomberg
23526,2017-11-13 09:11:00,1.31005,1.31010,1.30965,1.30965,0,bloomberg
23527,2017-11-13 09:12:00,1.30965,1.30965,1.30910,1.30950,0,bloomberg
23528,2017-11-13 09:13:00,1.30945,1.30965,1.30945,1.30955,0,bloomberg
23529,2017-11-13 09:14:00,1.30955,1.30965,1.30925,1.30925,0,bloomberg
23530,2017-11-13 09:15:00,1.30925,1.30965,1.30915,1.30965,0,bloomberg
23531,2017-11-13 09:16:00,1.30965,1.30965,1.30935,1.30935,0,bloomberg
23532,2017-11-13 09:17:00,1.30935,1.30935,1.30915,1.30925,0,bloomberg
23533,2017-11-13 09:18:00,1.30925,1.30935,1.30905,1.30925,0,bloomberg
23534,2017-11-13 09:19:00,1.30925,1.30930,1.30905,1.30925,0,bloomberg
23535,2017-11-13 09:20:00,1.30925,1.30925,1.30905,1.30915,0,bloomberg
23536,2017-11-13 09:21:00,1.30915,1.30915,1.30905,1.30905,0,bloomberg
23537,2017-11-13 09:22:00,1.30905,1.30905,1.30895,1.30905,0,bloomberg
23538,2017-11-13 09:23:00,1.30905,1.30905,1.30895,1.30895,0,bloomberg
23539,2017-11-13 09:24:00,1.30895,1.30905,1.30820,1.30845,0,bloomberg
23540,2017-11-13 09:25:00,1.30845,1.30895,1.30835,1.30860,0,bloomberg
23541,2017-11-13 09:26:00,1.30855,1.30865,1.30830,1.30835,0,bloomberg
23542,2017-11-13 09:27:00,1.30835,1.30855,1.30830,1.30845,0,bloomberg
23543,2017-11-13 09:28:00,1.30845,1.30855,1.30845,1.30855,0,bloomberg
23544,2017-11-13 09:29:00,1.30855,1.30855,1.30825,1.30825,0,bloomberg
23545,2017-11-13 09:30:00,1.30825,1.30835,1.30805,1.30825,0,bloomberg
...,...,...,...,...,...,...,...
62292,2017-06-30 10:34:00,1.29955,1.29955,1.29900,1.29905,0,bloomberg
62293,2017-06-30 10:35:00,1.29905,1.29945,1.29895,1.29940,0,bloomberg
62294,2017-06-30 10:36:00,1.29940,1.29940,1.29875,1.29880,0,bloomberg
62295,2017-06-30 10:37:00,1.29880,1.29885,1.29850,1.29880,0,bloomberg
62296,2017-06-30 10:38:00,1.29885,1.29945,1.29885,1.29915,0,bloomberg
62297,2017-06-30 10:39:00,1.29915,1.29955,1.29900,1.29955,0,bloomberg
62298,2017-06-30 10:40:00,1.29955,1.29955,1.29915,1.29915,0,bloomberg
62299,2017-06-30 10:41:00,1.29915,1.29945,1.29905,1.29935,0,bloomberg
62300,2017-06-30 10:42:00,1.29935,1.29945,1.29905,1.29905,0,bloomberg
62301,2017-06-30 10:43:00,1.29905,1.29915,1.29835,1.29845,0,bloomberg
62302,2017-06-30 10:44:00,1.29845,1.29875,1.29835,1.29855,0,bloomberg
62303,2017-06-30 10:45:00,1.29855,1.29880,1.29855,1.29865,0,bloomberg
62304,2017-06-30 10:46:00,1.29865,1.29870,1.29840,1.29845,0,bloomberg
62305,2017-06-30 10:47:00,1.29845,1.29855,1.29835,1.29855,0,bloomberg
62306,2017-06-30 10:48:00,1.29855,1.29855,1.29845,1.29855,0,bloomberg
62307,2017-06-30 10:49:00,1.29855,1.29885,1.29845,1.29885,0,bloomberg
62308,2017-06-30 10:50:00,1.29885,1.29915,1.29885,1.29915,0,bloomberg
62309,2017-06-30 10:51:00,1.29915,1.29925,1.29915,1.29925,0,bloomberg
62310,2017-06-30 10:52:00,1.29925,1.29925,1.29905,1.29915,0,bloomberg
62311,2017-06-30 10:53:00,1.29915,1.29925,1.29915,1.29925,0,bloomberg
62312,2017-06-30 10:54:00,1.29925,1.29925,1.29915,1.29915,0,bloomberg
62313,2017-06-30 10:55:00,1.29915,1.29935,1.29915,1.29935,0,bloomberg
62314,2017-06-30 10:56:00,1.29935,1.29985,1.29930,1.29985,0,bloomberg
62315,2017-06-30 10:57:00,1.29985,1.29985,1.29925,1.29925,0,bloomberg
62316,2017-06-30 10:58:00,1.29925,1.29945,1.29925,1.29935,0,bloomberg
62317,2017-06-30 10:59:00,1.29935,1.29935,1.29860,1.29865,0,bloomberg
62318,2017-06-30 11:00:00,1.29865,1.29890,1.29820,1.29825,0,bloomberg
62319,2017-06-30 11:01:00,1.29825,1.29825,1.29775,1.29785,0,bloomberg
62320,2017-06-30 11:02:00,1.29785,1.29810,1.29775,1.29805,0,bloomberg
62321,2017-06-30 11:03:00,1.29805,1.29815,1.29785,1.29800,0,bloomberg

In [57]:
con = sqlalchemy.create_engine('mysql://root:nasdaq93@127.0.0.1/hedge_fund') 
gbpusd.to_sql('gbpusd', con, if_exists = 'append')

/home/michal/anaconda3/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py:1569: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  cursor.execute('SELECT @@tx_isolation')

In [58]:
data = data[data['INSTRUMENT'] == 'EURUSD']
data = data.drop('INSTRUMENT', 1)
data['volume'] = 0
data['source'] = 'bloomberg'
data.to_sql('eurusd', con, if_exists = 'append')

In [64]:
data0 = data[data['INSTRUMENT'] == 'EURPLN']
data0 = data0.drop('INSTRUMENT', 1)
data0['volume'] = 0
data0['source'] = 'bloomberg'
data0.to_sql('eurpln', con, if_exists = 'append')

In [65]:
data0 = data[data['INSTRUMENT'] == 'AUDUSD']
data0 = data0.drop('INSTRUMENT', 1)
data0['volume'] = 0
data0['source'] = 'bloomberg'
data0.to_sql('audusd', con, if_exists = 'append')

In [66]:
data0 = data[data['INSTRUMENT'] == 'USDJPY']
data0 = data0.drop('INSTRUMENT', 1)
data0['volume'] = 0
data0['source'] = 'bloomberg'
data0.to_sql('usdjpy', con, if_exists = 'append')